on:
  push: 
    branches: [ main, develop ]

jobs:
  first_job:
    runs-on: ubuntu-latest

    # NOTE THAT
    # you can reference an action with either {owner}{repo}@{ref} 
    # or ./path/to/dir syntax in your workflow file.

    steps:
      # This step check out a copy of your repository
      - name: First step - check out repository
        uses: actions/checkout@v4
      # This step references the directory that contains the action
      - name: Use local action hellow-word-action
        uses: ./.github/actions/hello-world-action
      # This step references the directory that contains the action
      - name: Use local action io-action
        uses: ./.github/actions/io-action
        id: example-action
        with:
          file-path: "${{ github.workspace }}/.github/text/input.txt"
      # Show io result
      - name: Show result
        run: cat ${{ steps.example-action.outputs.results-file }}
      # This step adds an action from a different repository. Syntax: {owner}/{repo}@{ref}
      - name: Setup Node from another repo
        uses: actions/setup-node@v4
      # This step references a container on Docker Hub. Syntax: docker://{image}:{tag}
      - name: Alpine linux from Docker Hub
        uses: docker://alpine:3.8
      # This step references an action using a tag
      - name: Javascript action v1.0.1
        uses: actions/javascript-action@v1.0.1
      # This step references an action using a SHA digest
      - name: Javascript action by SHA
        uses: actions/javascript-action@a824008085750b8e136effc585c3cd6082bd575f
      # This step references an action using a branch
      - name: Javascript action by main branch
        uses: actions/javascript-action@main

